#!/bin/zsh


SPACESHIP_PROMPT_ORDER=(
    user          # Username section
    host          # Hostname section
    dir           # Current directory section
    git           # Git section (git_branch + git_status)
    venv          # Virtual Environment
    exec_time     # Execution time
    jobs          # Background jobs indicator
    exit_code     # Exit code section
    char          # Prompt character
)

SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true
# SPACESHIP_CHAR_SYMBOL=""
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_DIR_PREFIX="in "
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_TIME_SHOW=false
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_VI_MODE_SHOW=false

autoload -U promptinit; promptinit
prompt spaceship
