#! /bin/bash

pip install jupyter_ascending notebook && \
python -m jupyter nbextension    install jupyter_ascending --sys-prefix --py && \
python -m jupyter nbextension     enable jupyter_ascending --sys-prefix --py && \
python -m jupyter serverextension enable jupyter_ascending --sys-prefix --py

jupyter nbextension     list
jupyter serverextension list
