#!/bin/sh

alias p3='python3'

alias ls='eza --icons'
alias la='eza --icons -A'
alias ll='eza --icons -l'
alias lla='eza --icons -lA'
alias lt='eza --icons --tree'
alias ltl='eza --icons --tree -l'
alias lta='eza --icons --tree -A'
alias ltla='eza --icons --tree -Al'

alias cp='cp -rvi'
alias rm='rm -vi'
alias rsync='rsync -urvP'

alias rclone_copy='rclone --drive-server-side-across-configs -vv --transfers 3 --stats=15s --drive-chunk-size 128M copy'

alias dotfiles="git --git-dir=$HOME/work/repos/dotfiles --work-tree=$HOME"

alias extend_kb_mouse="ssh -YC {hostname} x2x -east -to :0"

alias code="/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron"
