theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
shell = ["zsh"]
cursorline = true
cursorcolumn = false
undercurl = true
bufferline = "always"
color-modes = true
true-color = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true

[editor.indent-guides]
render = true
character = '|'
skip-levels = 0

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']

