theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
shell = ["zsh"]
cursorline = true
cursorcolumn = false
undercurl = true
bufferline = "always"
color-modes = true
true-color = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true

[editor.indent-guides]
render = true
character = '|'
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
H = "goto_first_nonwhitespace"
L = "goto_line_end"
A-l = "jump_view_right"
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
