[[language]]
name = "python"

auto-format = true
[language.formatter]
command = "black"
args = [ "--quiet", "--line-length=120", "-" ]

language-servers = ["pylsp"]

[language-server.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = true}
pylint = {enabled = false}
yapf = {enabled = true}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
